using ZXCalculus
using Vega, DataFrames

function gen_cir()
    circ = ZXCircuit(5)
    push_gate!(circ, Val{:X}(), 5, 1//1)
    push_gate!(circ, Val{:H}(), 5)
    push_gate!(circ, Val{:Z}(), 5)
    push_gate!(circ, Val{:CNOT}(), 5, 4)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 1)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:CNOT}(), 5, 4)
    push_gate!(circ, Val{:Z}(), 4, 1//4)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 1)
    push_gate!(circ, Val{:CNOT}(), 4, 1)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:Z}(), 1, 1//4)
    push_gate!(circ, Val{:Z}(), 4, 7//4)
    push_gate!(circ, Val{:CNOT}(), 4, 1)
    push_gate!(circ, Val{:CNOT}(), 5, 4)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 3)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:CNOT}(), 5, 4)
    push_gate!(circ, Val{:Z}(), 4, 1//4)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 3)
    push_gate!(circ, Val{:CNOT}(), 4, 3)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:Z}(), 3, 1//4)
    push_gate!(circ, Val{:Z}(), 4, 7//4)
    push_gate!(circ, Val{:H}(), 5)
    push_gate!(circ, Val{:Z}(), 5)
    push_gate!(circ, Val{:CNOT}(), 4, 3)
    push_gate!(circ, Val{:CNOT}(), 5, 4)
    push_gate!(circ, Val{:H}(), 5)
    push_gate!(circ, Val{:Z}(), 5)
    push_gate!(circ, Val{:CNOT}(), 5, 3)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 2)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:CNOT}(), 5, 3)
    push_gate!(circ, Val{:Z}(), 3, 1//4)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 2)
    push_gate!(circ, Val{:CNOT}(), 3, 2)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:H}(), 5)
    push_gate!(circ, Val{:Z}(), 2, 1//4)
    push_gate!(circ, Val{:Z}(), 3, 7//4)
    push_gate!(circ, Val{:Z}(), 5)
    push_gate!(circ, Val{:CNOT}(), 3, 2)
    push_gate!(circ, Val{:CNOT}(), 5, 3)
    push_gate!(circ, Val{:H}(), 5)
    push_gate!(circ, Val{:Z}(), 5)
    push_gate!(circ, Val{:CNOT}(), 5, 2)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 1)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:CNOT}(), 5, 2)
    push_gate!(circ, Val{:Z}(), 2, 1//4)
    push_gate!(circ, Val{:Z}(), 5, 7//4)
    push_gate!(circ, Val{:CNOT}(), 5, 1)
    push_gate!(circ, Val{:CNOT}(), 2, 1)
    push_gate!(circ, Val{:Z}(), 5, 1//4)
    push_gate!(circ, Val{:Z}(), 1, 1//4)
    push_gate!(circ, Val{:Z}(), 2, 7//4)
    push_gate!(circ, Val{:H}(), 5)
    push_gate!(circ, Val{:Z}(), 5)
    push_gate!(circ, Val{:CNOT}(), 2, 1)
    push_gate!(circ, Val{:CNOT}(), 5, 2)
    push_gate!(circ, Val{:CNOT}(), 5, 1)
    return circ
end

cir = gen_cir()
cir2 = phase_teleportation(cir)
tcount(cir2)
cir3 = clifford_simplification(cir2)
tcount(cir3)
plot(cir2)
plot(cir3)
