include("./interface.jl")
include("./fusion.jl")
include("./hadamard.jl")
include("./identity1.jl")
include("./identity2.jl")
include("./pi_rule.jl")
include("./copy_rule.jl")
include("./bialgebra.jl")
include("./local_comp.jl")
include("./pivot1.jl")
include("./pivot_boundary.jl")
include("./pivot2.jl")
include("./pivot3.jl")
include("./pivot_gadget.jl")
include("./identity_remove.jl")
include("./gadget_fusion.jl")
include("./scalar.jl")

# Compatibility aliases for backward compatibility
@deprecate Rule{:f}() FusionRule()
@deprecate Rule{:h}() XToZRule()
@deprecate Rule{:i1}() Identity1Rule()
@deprecate Rule{:i2}() HBoxRule()
@deprecate Rule{:pi}() PiRule()
@deprecate Rule{:c}() CopyRule()
@deprecate Rule{:b}() BialgebraRule()
@deprecate Rule{:lc}() LocalCompRule()
@deprecate Rule{:p1}() Pivot1Rule()
@deprecate Rule{:pab}() PivotBoundaryRule()
@deprecate Rule{:p2}() Pivot2Rule()
@deprecate Rule{:p3}() Pivot3Rule()
@deprecate Rule{:pivot}() PivotGadgetRule()
@deprecate Rule{:id}() IdentityRemovalRule()
@deprecate Rule{:gf}() GadgetFusionRule()
@deprecate Rule{:scalar}() ScalarRule()
